### ISSUE TITLE
Pointing to Open Data SE

### ISSUE THREAD

**Issue by jalbertbowden** [USAID/USAID-Data-Services#30]
Provide some context and examples to your users before you point blindly to a third party source, especially when only you have the institutional knowledge to answer certain questions pertaining to your work. Moreover, this kind of historical context should be owned by you, the canonical source, vs a third party that may go away one day. Lastly, I am unaware of anyone from USAID that is active on the site; not saying there aren't any, but if there are, your contributions are bare minimum at best. It is ridiculous that you point your users to a community that you are not active in.  

Pointing blankly to OD SE results in questions like the screenshot below:  
![Screenshot of USAID Question with Zero Context](https://user-images.githubusercontent.com/46432/48499125-b4c3a000-e805-11e8-9bd9-f3b76a4decf8.png)  

Questions best answered by the canonical source, i.e., you, shouldn't by default be sent to a third party. 
Without your team actively engaging, questions are not going to be answered as prompt or as matter of fact as they could be.  

Open Data SE is an international volunteer community, not the federal government's third party volunteer forum.  

This is an ongoing issue that a number of federal agencies continue to contribute to. It's not fair to your users or our community.

**Comment by MorganDaniels** [comment]
Thank you for your comment to the USAID Data Services Team.  Please accept my apology for the mistaken StackExchange link from the Help menu of the Development Data Library.  Our intent was to automatically populate the feedback form with the tag usaidopen so that questions would be routed to our team, rather than sent to the Open Data SE community as a whole.  I have fixed that error in our Help menu, and all future messages generated from the DDL will be tagged appropriately. I also appreciate your feedback that our team has not had active engagement in the Open Data SE community.  We recognize our recent absence there, and our team is working to ensure a quick response to all open questions regarding USAID open data on Stack Exchange, and a swift response to all new questions (beginning with this one and “Are datasets available for download?” which you included here).  I look forward to meaningful engagement with this community. Please feel free to continue the conversation here, or to email us at dataservices@usaid.gov to discuss further.
 
Best wishes,
Morgan Daniels

**Comment by philshem** [comment]
FYI - can find open questions tagged with [`usaidopen`](
https://opendata.stackexchange.com/questions/tagged/usaidopen) with this query, and feel free to "watch" the tag in order to get some email notifications 😃 

<img width="638" alt="image" src="https://user-images.githubusercontent.com/4997607/48558931-c03cc700-e8ea-11e8-96f0-2fe97a0703d3.png">

or a list of unanswered questions

https://opendata.stackexchange.com/questions/tagged/usaidopen?sort=unanswered

or an RSS feed

https://opendata.stackexchange.com/feeds/tag/usaidopen

or even add email subscription for new questions

https://stackexchange.com/filters

**Comment by MorganDaniels** [comment]
Thank you- much appreciated!
